package com.briozing.automation.utils;

public enum TestSteps {
    STEP_GET_ALL_BOOKING_ID,
    STEP_GET_BOOKING_BY_ID,
    STEP_GET_ID_BY_NAME,
    STEP_GET_ID_BY_DATE,
    STEP_CREATE_BOOKING,
    STEP_POST_JSON,
    STEP_GET_TOKEN,
    STEP_UPDATE_BOOKING,
    STEP_PARTIAL_UPDATE_BOOKING,
    STEP_DELETE_BOOKING
}
